# params.yaml
# This file defines hyperparameters and configuration values for the DVC pipeline.
# Each section corresponds to a pipeline stage in dvc.yaml.

data_ingestion:
  # Fraction of the dataset to be used for testing (e.g., 0.2 = 20% test data, 80% train data)
  test_size: 0.2

feature_engineering:
  # Maximum number of features to generate/select during feature engineering
  max_features: 50

model_building:
  # Number of trees/estimators for the ensemble model (e.g., RandomForest, GradientBoosting)
  n_estimators: 25

  # Learning rate for boosting algorithms (controls how much each tree contributes)
  learning_rate: 0.1
